sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d #This comes from the result of encrypting service-account.json
  - curl https://sdk.cloud.google.com | bash > /dev/null; #download google sdk and install it
  - source $HOME/google-cloud-sdk/path.bash.inc #This two commands will install google sdk and this came from an instruction.
  - gcloud components update kubectl #install kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project test-myrestsvc #This is the project ID in google cloud project.
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials myrestsvc-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t rwuniard/myrestsvc -f ./Dockerfile.dev ./


deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master #only happens on master branch