apiVersion: skaffold/v2beta12
kind: Config
build:
  local: # this means don't push to your git repo
    push: false # when the setting is set to false.
  artifacts:
    - image: rwuniard/myrestsvc
      context: .
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: '**/*.js' # This means detect any javascript changes and copy it to target in kubernetes
            dest: .
deploy:
  kubectl:
    manifests:
      - k8s/myrest-server-deployment.yaml
      - k8s/myrest-server-cluster-ip-service.yaml
      - k8s/ingress-service.yaml